### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by onefish51** [wan-h/AnimeGAN_pytorch#2]
when I train Shinkai on 1 GPU ,  INIT EPOCH is over , train EPOCH is start (epoch_current == 11), an error occurred !
```sh
Traceback (most recent call last):
  File "scripts/train_net.py", line 87, in <module>
    main()
  File "scripts/train_net.py", line 84, in main
    train(cfg, args.local_rank, args.distributed, logger_name, output_dir)
  File "animeganv2/lib/trainer.py", line 94, in train
    do_train(
  File "animeganv2/engine/trainer.py", line 183, in do_train
    loss_g.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by wan-h** [comment]
What's your batchsize, try reduce your batchsize, I  can train this model on 1 GPU successfully.
